### ISSUE TITLE
graph deploy error

### ISSUE THREAD

**Issue by slw07** [PatrickAlphaC/graph-nft-marketplace-fcc#12]
hi,Patrick，When I was following your tutorial video to implement graph deploy --stutio, an error occurred: Failed to upload subgraph to IPFS: Failed to upload file to IPFS:, The html returned contains 504: Gateway time-out. What is the reason for this
![Uploading 1714483517068.jpg…]()

**Comment by PatrickAlphaC** [comment]
Hmm... I'm probably going to do an overhaul of this tutorial. Going to close this for now. I'd say skip over this section for now.

**Comment by slw07** [comment]
Really? I just learned this part. Don't you want to use graph?
