### ISSUE TITLE
 Images are not displayed on localhost:3000

### ISSUE THREAD

**Issue by SkyLian66** [PatrickAlphaC/graph-nft-marketplace-fcc#4]
I run yarn hardhat run scripts/mint-and-list-item.js --network goerli. 
Minting NFT...
Approving NFT...
Listing NFT...
NFT Listed!
My graph Playground seem work fine:
  "data": {
    "activeItems": [
      {
        "id": "0x40xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "buyer": "0x0000000000000000000000000000000000000000",
        "seller": "0xd5d7b1f64240b4e5637c721877d4c59d081691f6",
        "nftAddress": "0xd3f397a0c17d4ef792f0da12ec8de93990d8a80c"
      },
      {
        "id": "0x50xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "buyer": "0x0000000000000000000000000000000000000000",
        "seller": "0xd5d7b1f64240b4e5637c721877d4c59d081691f6",
        "nftAddress": "0xd3f397a0c17d4ef792f0da12ec8de93990d8a80c"
      },
      {
        "id": "0x60xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "buyer": "0x0000000000000000000000000000000000000000",
        "seller": "0xd5d7b1f64240b4e5637c721877d4c59d081691f6",
        "nftAddress": "0xd3f397a0c17d4ef792f0da12ec8de93990d8a80c"
      }
    ],
    "itemListeds": [
      {
        "id": "0x40xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "seller": "0xd5d7b1f64240b4e5637c721877d4c59d081691f6",
        "nftAddress": "0xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "tokenId": "4"
      },
      {
        "id": "0x50xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "seller": "0xd5d7b1f64240b4e5637c721877d4c59d081691f6",
        "nftAddress": "0xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "tokenId": "5"
      },
      {
        "id": "0x60xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "seller": "0xd5d7b1f64240b4e5637c721877d4c59d081691f6",
        "nftAddress": "0xd3f397a0c17d4ef792f0da12ec8de93990d8a80c",
        "tokenId": "6"
      }
    ]
  }
}
What is the problem? Everything seems going well! But nft marketplace image no show up!
Can you help me with the issue!
Thanks!

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be


Thank you!
