### ISSUE TITLE
graph init --studio nft-marketplace ERROR

### ISSUE THREAD

**Issue by RohitAggarwal04** [PatrickAlphaC/graph-nft-marketplace-fcc#7]
![Screenshot 2023-03-23 144328](https://user-images.githubusercontent.com/97400593/227156695-fb5cd5e2-f11b-4e9f-a916-f3613fa5343a.png)

**Stuck here for hours . someone please help!**

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
